environment:
  matrix:
    - node_version: 7
      BROWSER: chrome

    - node_version: 7
      BROWSER: firefox

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

test_script:
  - node --version
