version: '3'
# to run test in docker execute:
# docker-compose run test npm run test:docker
services:
  test:
    environment:
    - ACCOUNT_SID=${ACCOUNT_SID}
    - API_KEY_SID=${API_KEY_SID}
    - API_KEY_SECRET=${API_KEY_SECRET}
    - TOPOLOGY=${TOPOLOGY}
    image: twilio-video-js-test-${BROWSER}-${BVER}
    build:
      args:
      - USE_BROWSER=${BROWSER}
      - USE_BVER=${BVER}
      context: .
      dockerfile: docker/test/Dockerfile
    working_dir: /opt/app
    container_name: "test-${BROWSER}-${BVER}"
    volumes:
      - "./:/opt/app"
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/app/node_modules
