# https://hub.docker.com/r/browserless/chrome/dockerfile/
FROM circleci/node:lts-browsers

# install selected browser / version
ENV BROWSER='chrome'
ENV BVER='stable'

# specify default command to run container w/o arguments.
CMD ["bash"]
