name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}

jobs:
  check:
    name: ${{ matrix.name }}
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest-large
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: lint
            run: npm run lint
          - name: build
            run: npm run build:quick
          - name: unit-tests
            run: npm run test:unit
          - name: ssr-tests
            run: |
              npm run build:es5
              npm run test:serversiderender
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Artifactory OIDC Auth
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: ./.github/actions/artifactory-oidc
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: ${{ matrix.run }}
